[package]
name = "fluid"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.59"
syn = "1.0.99"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"

[dependencies.web-sys]
version = "0.3.59"
features = [
  "Window",
  "Document",
  "Element",
  "Text",
  "HtmlElement"
]
