[build]
target="wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", "--cfg=web_sys_unstable_apis", "-Z", "macro-backtrace"]

[unstable]
build-std= ["std", "panic_abort"]
