#!/bin/sh

case $1 in
	"b" | "build")
    cd fluid-example
		cargo build --release
    wasm-bindgen --out-dir ./pkg --target no-modules \
    $CARGO_TARGET_DIR/wasm32-unknown-unknown/release/fluid_example.wasm
    curl http://localhost:8080/mark-stale
	;;
	"s" | "serve")
    cd fluid-example
		python3 server.py
	;;
	"d" | "document")
    cargo doc --document-private-items --open
	;;
	"w" | "watch")
		cargo watch\
      -w fluid/Cargo.toml\
      -w fluid/src\
      -w fluid-example/Cargo.toml\
      -w fluid-example/src\
      -w fluid-macro/Cargo.toml\
      -w fluid-macro/src\
      -s "$0 build"
	;;
	*)
		echo "build [(b)uild | (s)erve | (d)ocument | (w)atch]"
esac
