[package]
name = "fluid-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
maud = "0.25.0"
quote = "1.0.33"
syn = "2.0.37"
fluid = { path = "../fluid" }
proc-macro2 = "1.0.67"
